updating and clarifying documentation
fluffos/fluffos pull request #916
Opened 2022-09-02 03:37 UTC by gesslar

* Adding names to parameter args
* Adding examples
* Adding information that was missing from various efuns
* Slight formatting modifications in places

2022-09-02 10:55 UTC, oiuv commented on docs/efun/interactive/printf.md
> +    sprintf, sscanf(3)
这里sprintf可以改为 sprintf(3)

2022-09-02 10:57 UTC, oiuv commented on docs/efun/objects/all_inventory.md
> +    object *all_inventory( object ob);
这里最好统一呀，左右空格要么都有，要么都没有。

2022-09-02 11:00 UTC, oiuv approved these changes

2022-09-03 01:24 UTC, oiuv requested changes
good job

2022-09-03 01:47 UTC, thefallentree approved these changes

2022-09-03 01:48 UTC, merged